# Generated by Django 4.2.3 on 2023-08-03 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variation_vale',
            new_name='variation_value',
        ),
    ]
